apiVersion: v1
kind: Service
metadata:
  name: session
  labels:
    app: session
spec:
  ports:
  - port: 5001
    targetPort: 5001
  selector:
    app: session
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: session
  labels:
    app: session
spec:
  replicas: 2
  selector:
    matchLabels:
      app: session
  template:
    metadata:
      labels:
        app: session
    spec:
      containers:
        - name: session
          image: telepathy.azurecr.io/dev/session
          volumeMounts:
            - name: session-config
              mountPath: /app/session-config
              readOnly: true
          command: ["dotnet", "SessionManager.dll"]
          ports:
          - containerPort: 5001
          resources:
            requests:
              cpu: "1" 
          env:
          - name: TELEPATHY_DISPATCHER_IP
            valueFrom:
              configMapKeyRef:
                name: dispatcher-config
                key: dispatcherIpAddress

          - name: TELEPATHY_SESSION_CONFIG_PATH
            value: "/app/session-config/session.json"

          - name: TELEPATHY_WORKING_DIR
            value: /app/

          - name: TELEPATHY_QUEUE_ADDRESSES
            value: nsqlookupd-0.nsqlookupd:4161;nsqlookupd-1.nsqlookupd:4161;nsqlookupd-2.nsqlookupd:4161
      volumes:
        - name: session-config
          secret:
            secretName: session-secret
 
#kubectl create secret generic session-secret --from-file=./session.json